server:
  servlet:
    session:
      tracking-modes: cookie

logging:
  level:
    root: info
    com.lolup.lolup_project: debug

spring:
  profiles:
    include:
      - oauth
      - db

mybatis:
  type-aliases-package: com.lolup.lolup_project
  mapper-locations: mybatis/mapper/**/*.xml

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
