spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ENC(gKZYnBvjAjedTjh3b9ZuuEGOAc6+yQKJ7vw1jq4xw143s7KcstlVg8NztcPRKjzJlWDo/rQlFRngtC3FcnowYFNhgGtEMZdzwow9elTByMlAMEFvlvmkKDihHQ0v4uDH)
    username: ENC(TrfO7cYfJec5zTygpY/GvA==)
    password: ENC(aGwjP5UFAUbohPv29yVHXxSncI8okXT5)
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    hibernate:
      # ddl; data definition language
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
#    open-in-view: false

logging:
  level:
    root: info
    com.lolup.lolup_project: info

front:
  domain: http://d2fh37v4sikqk8.cloudfront.net
  redirect_url: http://d2fh37v4sikqk8.cloudfront.net/oauth2/login?token=


