spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/lolup
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

google:
  client-id: ENC(xkPiPi3rI37x0QR0Xp3/wpGfa5N5wK0IkkcK1+D2FUgRkeT3meZTisytQQ37Yq03wYBvI5HnJAs3RCxOrhZE6DrL7rjI5YfKdPoop1l2BI4DL5+YlEI0mg==)
  client-secret: ENC(dMmQIPkVnjU3Y24doVDVIyJquIrjt5QYKfz8WrOUMfjeYohs1hJYuw==)

kakao:
  clientId: ENC(jOmRBZz9NjpeenL+DaCYk4S6xDC+wo07h0NkNINMfRw3scqG0DNBJUlvyDqj9KCE)
  clientSecret: ENC(mylpxosRyT//agdBD7W8svsSHAPOimOnbGdN+gLWD2tMdapBCgAcNuZWMi1An4Fu)

logging:
  level:
    root: info
    com.lolup.lolup_project: debug
    org.hibernate.SQL: debug

security:
  jwt:
    token:
      secret-key: ENC(0FawlMK9+/6FNbjFjFHX5GzZ+rjy6YOqOClDge/62ceux8+9fRm1hSGkzsFZkgk37RcxgMUXDOMXeYTAyOaKuY/a+sZyOC9l+TgibsuHJ9Y=)
      access:
        expire-length: 3600000 #1시간
      refresh:
        expire-length: 1210000000 #14일
  riot:
    api-key: ENC(i1mdH6yxdMM9/QwVBY0zhMvys1j8PZKBcLY+6wc0s9LykYYZB5B2ZE4HUlgXXMfVDgrZBfCfe4A=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

front:
  domain: http://localhost:3000
