server:
  servlet:
    session:
      tracking-modes: cookie

spring:
  profiles:
    default: dev

  datasource:
    url: ENC(gKZYnBvjAjedTjh3b9ZuuEGOAc6+yQKJ7vw1jq4xw143s7KcstlVg8NztcPRKjzJlWDo/rQlFRngtC3FcnowYFNhgGtEMZdzwow9elTByMlAMEFvlvmkKDihHQ0v4uDH)
    username: ENC(TrfO7cYfJec5zTygpY/GvA==)
    password: ENC(aGwjP5UFAUbohPv29yVHXxSncI8okXT5)
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: mybatis-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true

  security:
    oauth2:
      client:
        registration:
          # 네이버는 Spring Security를 공식 지원하지 않기 때문에 CommonOAuth2Provider 에서 해주는 값들을 수동으로 입력한다.
          naver:
            client-id: ENC(xgr1Vshedp/+SaEaO1ytFHtD2MnEsRAYw44/WQsmNNI=)
            client-secret: ENC(oQ8kqphaiR1i0Jcl8Gogf91CQchdjOzy)
            #            clientAuthenticationMethod: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope:
              - name
              - email
              - profile
              - profile_image
            client-name: Naver

          google:
            client-id: ENC(xkPiPi3rI37x0QR0Xp3/wpGfa5N5wK0IkkcK1+D2FUgRkeT3meZTisytQQ37Yq03wYBvI5HnJAs3RCxOrhZE6DrL7rjI5YfKdPoop1l2BI4DL5+YlEI0mg==)
            client-secret: ENC(dMmQIPkVnjU3Y24doVDVIyJquIrjt5QYKfz8WrOUMfjeYohs1hJYuw==)
            authorization-grant-type: authorization_code
            accessTokenValiditySeconds: 1*60*60;
            scope:
              - profile
              - email

          kakao:
            clientId: ENC(jOmRBZz9NjpeenL+DaCYk4S6xDC+wo07h0NkNINMfRw3scqG0DNBJUlvyDqj9KCE)
            clientSecret: ENC(mylpxosRyT//agdBD7W8svsSHAPOimOnbGdN+gLWD2tMdapBCgAcNuZWMi1An4Fu)
            redirectUri: "{baseUrl}/login/oauth2/code/kakao"
            authorizationGrantType: authorization_code
            client-authentication-method: POST
            clientName: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  secret: ENC(b/GysgadqZoCeK/Y4ctB8dumwZSuOuf5ppvC3K3v20A=)

mybatis:
  type-aliases-package: com.lolup.lolup_project
  mapper-locations: mybatis/mapper/**/*.xml

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
