spring:
  datasource:
    url: ENC(gKZYnBvjAjedTjh3b9ZuuEGOAc6+yQKJ7vw1jq4xw143s7KcstlVg8NztcPRKjzJlWDo/rQlFRngtC3FcnowYFNhgGtEMZdzwow9elTByMlAMEFvlvmkKDihHQ0v4uDH)
    username: ENC(TrfO7cYfJec5zTygpY/GvA==)
    password: ENC(aGwjP5UFAUbohPv29yVHXxSncI8okXT5)
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: mybatis-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true