spring:
  security:
    oauth2:
      client:
        registration:
          # 네이버는 Spring Security를 공식 지원하지 않기 때문에 CommonOAuth2Provider 에서 해주는 값들을 수동으로 입력한다.
          naver:
            client-id: ENC(xgr1Vshedp/+SaEaO1ytFHtD2MnEsRAYw44/WQsmNNI=)
            client-secret: ENC(oQ8kqphaiR1i0Jcl8Gogf91CQchdjOzy)
#            clientAuthenticationMethod: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope:
              - name
              - email
              - profile
              - profile_image
            client-name: Naver

          google:
            client-id: ENC(xkPiPi3rI37x0QR0Xp3/wpGfa5N5wK0IkkcK1+D2FUgRkeT3meZTisytQQ37Yq03wYBvI5HnJAs3RCxOrhZE6DrL7rjI5YfKdPoop1l2BI4DL5+YlEI0mg==)
            client-secret: ENC(dMmQIPkVnjU3Y24doVDVIyJquIrjt5QYKfz8WrOUMfjeYohs1hJYuw==)
            authorization-grant-type: authorization_code
            accessTokenValiditySeconds: 1*60*60;
            scope:
              - profile
              - email

          kakao:
            clientId: e284a5e53a80a3d3df7523acbc658c21
            clientSecret: VfyxkGau1MMQDRrQbSJkffmjtkenXb1X
#            clientAuthenticationMethod: post
            redirectUri: "{baseUrl}/login/oauth2/code/kakao"
            authorizationGrantType: authorization_code
            client-authentication-method: POST
            clientName: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

