spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/lolup
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # ddl; data definition language
      ddl-auto: create # 이 옵션은 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다.
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

logging:
  level:
    root: info
    com.lolup.lolup_project: debug
    org.hibernate.SQL: debug

front:
  domain: http://localhost:3000
  redirect_url: http://localhost:3000/oauth2/login?token=

