spring:
  datasource:
    url: jdbc:mariadb://lolup-rds1.c7qm67jnhiks.ap-northeast-2.rds.amazonaws.com:3306/lolup
    username: admin
    password: lolup1234
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  type-aliases-package: com.lolup.lolup_project
  mapper-locations: mybatis/mapper/**/*.xml